"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/567EjL4Odv7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { NavigationMenuLink, NavigationMenuItem, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"
import { CardContent, Card } from "@/components/ui/card"

export function Layout() {
  return (
    <>
      <header className="w-full bg-gray-950 text-gray-50 py-4 px-6 md:px-12 flex items-center justify-between">
        <Link className="flex items-center gap-2" href="#">
          <PaletteIcon className="w-6 h-6" />
          <span className="text-xl font-bold">Acme Design</span>
        </Link>
        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuLink href="#">Home</NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink href="#">Work</NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink href="#">About</NavigationMenuLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuLink href="#">Contact</NavigationMenuLink>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
      </header>
      <main>
        <section className="w-full bg-gray-950 text-gray-50 py-24 px-6 md:px-12 flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="space-y-4 max-w-md">
            <h1 className="text-4xl font-bold">Jane Doe</h1>
            <h2 className="text-2xl font-medium">UI/UX Designer</h2>
            <p className="text-gray-400">
              I&lsquo;m a passionate UI/UX designer with a keen eye for detail and a love for creating intuitive and visually
              stunning digital experiences.
            </p>
          </div>
          <img
            alt="Jane Doe"
            className="rounded-full w-48 h-48 object-cover"
            height={400}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/400",
              objectFit: "cover",
            }}
            width={400}
          />
        </section>
        <section className="w-full bg-gray-100 dark:bg-gray-800 py-12 px-6 md:px-12">
          <div className="container mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Card>
              <img
                alt="Project 1"
                className="rounded-t-lg w-full h-48 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold">Project 1</h3>
                <p className="text-gray-500 dark:text-gray-400">A sleek and modern e-commerce website design.</p>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Project 2"
                className="rounded-t-lg w-full h-48 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold">Project 2</h3>
                <p className="text-gray-500 dark:text-gray-400">A clean and intuitive mobile app design.</p>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Project 3"
                className="rounded-t-lg w-full h-48 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold">Project 3</h3>
                <p className="text-gray-500 dark:text-gray-400">A visually striking branding and website design.</p>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Project 4"
                className="rounded-t-lg w-full h-48 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold">Project 4</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  A user-friendly dashboard design for a SaaS platform.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Project 5"
                className="rounded-t-lg w-full h-48 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold">Project 5</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  A modern and responsive website design for a creative agency.
                </p>
              </CardContent>
            </Card>
            <Card>
              <img
                alt="Project 6"
                className="rounded-t-lg w-full h-48 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold">Project 6</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  A sleek and modern mobile app design for a fitness tracking app.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="w-full bg-gray-950 text-gray-50 py-6 px-6 md:px-12 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <PaletteIcon className="w-6 h-6" />
          <span className="text-xl font-bold">Acme Design</span>
        </div>
        <div className="flex items-center gap-4">
          <Link className="text-gray-400 hover:text-gray-50" href="#">
            <TwitterIcon className="w-6 h-6" />
          </Link>
          <Link className="text-gray-400 hover:text-gray-50" href="#">
            <LinkedinIcon className="w-6 h-6" />
          </Link>
          <Link className="text-gray-400 hover:text-gray-50" href="#">
            <InstagramIcon className="w-6 h-6" />
          </Link>
        </div>
      </footer>
    </>
  )
}

function InstagramIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function PaletteIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z" />
    </svg>
  )
}


function TwitterIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
