/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/U1fLGff24rJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import React from 'react';
import { Button } from "@/components/ui/button";

export function yy() {
  return (
    <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg p-6">
      <div className="flex items-center justify-between mb-4">
        <div className="text-lg font-medium">May 2024</div>
        <div className="flex items-center gap-2">
          <Button size="icon" variant="ghost">
            <ChevronLeftIcon className="w-5 h-5" />
          </Button>
          <Button size="icon" variant="ghost">
            <ChevronRightIcon className="w-5 h-5" />
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-7 gap-2 text-center">
        <div className="text-gray-500 dark:text-gray-400 font-medium">Sun</div>
        <div className="text-gray-500 dark:text-gray-400 font-medium">Mon</div>
        <div className="text-gray-500 dark:text-gray-400 font-medium">Tue</div>
        <div className="text-gray-500 dark:text-gray-400 font-medium">Wed</div>
        <div className="text-gray-500 dark:text-gray-400 font-medium">Thu</div>
        <div className="text-gray-500 dark:text-gray-400 font-medium">Fri</div>
        <div className="text-gray-500 dark:text-gray-400 font-medium">Sat</div>
        <div className="text-gray-400 dark:text-gray-600">28</div>
        <div className="text-gray-400 dark:text-gray-600">29</div>
        <div className="text-gray-400 dark:text-gray-600">30</div>
        <div className="text-gray-400 dark:text-gray-600">1</div>
        <div className="text-gray-400 dark:text-gray-600">2</div>
        <div className="text-gray-400 dark:text-gray-600">3</div>
        <div className="text-gray-400 dark:text-gray-600">4</div>
        <div className="bg-gray-900 text-white rounded-full w-8 h-8 flex items-center justify-center dark:bg-gray-50">5</div>
        <div className="text-gray-400 dark:text-gray-600">6</div>
        <div className="text-gray-400 dark:text-gray-600">7</div>
        <div className="text-gray-400 dark:text-gray-600">8</div>
        <div className="text-gray-400 dark:text-gray-600">9</div>
        <div className="text-gray-400 dark:text-gray-600">10</div>
        <div className="text-gray-400 dark:text-gray-600">11</div>
      </div>
    </div>
  );
}

function ChevronLeftIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  );
}

function ChevronRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}
